const PEOPLE = [
 ['Ben Affleck',['ben affleck']],['SteveWillDoIt',['stevewilldoit','steve will do it']],['Kylie Jenner',['kylie jenner']],['Drake',['drake','champagne papi']],['MrBeast',['mrbeast','mr beast','jimmy donaldson']],['Travis Scott',['travis scott']],['LeBron James',['lebron james','lebron']],['Kim Kardashian',['kim kardashian']],['Cristiano Ronaldo',['cristiano ronaldo','ronaldo']],['Jake Paul',['jake paul']],['Taylor Swift',['taylor swift']],['Kai Cenat',['kai cenat']],['Logan Paul',['logan paul']],['Elon Musk',['elon musk']],['Tom Brady',['tom brady']],['Conor McGregor',['conor mcgregor']],['Kevin Hart',['kevin hart']],['Floyd Mayweather',['floyd mayweather']],['Lionel Messi',['lionel messi']],['Justin Bieber',['justin bieber']],['Beyoncé',['beyonce','beyoncé']],['Jay-Z',['jay-z','jay z']],['Rihanna',['rihanna']],['Selena Gomez',['selena gomez']],['Post Malone',['post malone']],['Bad Bunny',['bad bunny']],['Neymar',['neymar']],['Patrick Mahomes',['patrick mahomes']],['Stephen Curry',['stephen curry']],['Travis Kelce',['travis kelce']],['Tom Holland',['tom holland']],['Zendaya',['zendaya']],['Dwayne Johnson',['dwayne johnson','the rock']],['Ryan Reynolds',['ryan reynolds']],['Gordon Ramsay',['gordon ramsay']],['Mark Cuban',['mark cuban']],['Shaquille O’Neal',['shaquille o’neal','shaquille o\'neal','shaq']],['David Beckham',['david beckham']],['George Clooney',['george clooney']],['Oprah Winfrey',['oprah winfrey']],['Snoop Dogg',['snoop dogg']],['50 Cent',['50 cent']],['Lil Wayne',['lil wayne']],['Cardi B',['cardi b']],['Offset',['offset']],['Megan Thee Stallion',['megan thee stallion']],['Kendall Jenner',['kendall jenner']],['Paris Hilton',['paris hilton']],['MrBeast',['mrbeast']]
];
const QUERIES = [
 'celebrity (bought OR purchased OR mansion OR house OR yacht OR jet OR plane OR car OR watch OR jewelry) when:3d',
 'celebrity (bet OR wager OR gambling OR sportsbook) (million OR thousand OR dollars OR $) when:3d',
 'celebrity (investment OR invested OR stake OR acquisition OR business deal) (million OR billion OR dollars OR $) when:3d',
 'athlete (bought OR purchased OR mansion OR house OR car OR jet OR investment OR wager) when:3d',
 'rapper musician (bought OR purchased OR mansion OR house OR car OR jet OR watch OR jewelry OR investment) when:3d',
 'YouTuber influencer streamer (bought OR purchased OR spent OR mansion OR house OR car OR jet OR investment OR bet) when:3d',
 'actor actress celebrity (real estate OR mansion OR house OR luxury OR investment OR bought) when:3d',
 'celebrity (spending OR purchase OR deal OR contract) (million OR billion OR $) when:3d'
];
const DEMO=[
 ['Drake','Betting',500000,'Drake linked to a reported $500K sports wager','A high-dollar wager is being discussed across sports and entertainment coverage.','Reported','Sports / entertainment coverage'],
 ['MrBeast','Business',1800000,'MrBeast reveals a massive production budget','A behind-the-scenes discussion gives viewers a look at the scale of spending behind a major video.','Verified','YouTube interview'],
 ['Travis Scott','Luxury',3200000,'A new luxury purchase reportedly cost $3.2M','The purchase has sparked conversation about celebrity car collections and luxury spending.','Reported','Automotive publication'],
 ['LeBron James','Investment',2500000,'LeBron-linked investment draws attention','A reported investment puts another spotlight on athlete ownership and venture deals.','Reported','Business publication'],
 ['Kim Kardashian','Luxury',275000,'A luxury jewelry purchase gets the internet talking','A high-end piece worn in a recent appearance is being valued in the six figures.','Estimated','Luxury media'],
 ['Cristiano Ronaldo','Cars',1200000,'Ronaldo adds another serious car to the collection','The football star is known for a collection that includes expensive vehicles.','Reported','Automotive coverage'],
 ['Jake Paul','Betting',100000,'Jake Paul discusses a five-figure wager','A betting-related comment has fans debating the number.','Verified','Podcast / interview'],
 ['Taylor Swift','Real Estate',8500000,'Luxury property activity puts Swift back in the headlines','A reported property transaction is drawing attention from real-estate watchers.','Reported','Real estate coverage'],
 ['Kai Cenat','Creator',400000,'Kai Cenat talks about creator-level spending','A conversation gives viewers a glimpse into the cost of large creator projects.','Verified','Stream / interview'],
 ['Logan Paul','Business',1100000,'A seven-figure business deal surfaces','A new business move puts Logan Paul back on the money-moves leaderboard.','Reported','Business coverage']
];
function strip(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#x27;/g,"'").replace(/&#8217;/g,"’").replace(/&#x2019;/g,"’").replace(/\s+/g,' ').trim();}
function tag(xml,name){const m=xml.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>','i'));return m?strip(m[1]):'';}
function blocks(xml){return xml.match(/<item[\s\S]*?<\/item>/gi)||xml.match(/<entry[\s\S]*?<\/entry>/gi)||[];}
function linkOf(b){let m=b.match(/<link[^>]*href=["']([^"']+)["'][^>]*>/i);if(m)return m[1];m=b.match(/<link[^>]*>([\s\S]*?)<\/link>/i);return m?strip(m[1]):'';}
function sourceOf(b,link){const m=b.match(/<source[^>]*>([\s\S]*?)<\/source>/i);if(m)return strip(m[1]);try{return new URL(link).hostname.replace(/^www\./,'')}catch{return 'Google News'}}
function personFor(text){const t=text.toLowerCase();for(const [name,aliases] of PEOPLE){if(aliases.some(a=>t.includes(a)))return name;}return null;}
function amountFor(text){const t=text.replace(/,/g,'');const p=[/\$\s*([0-9]+(?:\.[0-9]+)?)\s*(billion|million|m|thousand|k)?/i,/([0-9]+(?:\.[0-9]+)?)\s*(billion|million|m|thousand|k)\s*(?:dollars|usd)?/i];for(const r of p){const m=t.match(r);if(!m)continue;let n=Number(m[1]);const u=(m[2]||'').toLowerCase();if(u==='billion')n*=1e9;else if(u==='million'||u==='m')n*=1e6;else if(u==='thousand'||u==='k')n*=1e3;return n;}return null;}
function moneyLabel(n){if(n==null)return 'Undisclosed';if(n>=1e9)return '$'+(n/1e9).toFixed(n%1e9?1:0)+'B';if(n>=1e6)return '$'+(n/1e6).toFixed(n%1e6?1:0)+'M';if(n>=1e3)return '$'+(n/1e3).toFixed(n%1e3?0:0)+'K';return '$'+n.toLocaleString();}
function category(text){const t=text.toLowerCase();if(/bet|wager|sportsbook|gambl/.test(t))return 'Betting';if(/mansion|house|home|estate|property|real estate/.test(t))return 'Real Estate';if(/car|ferrari|lamborghini|porsche|rolls|vehicle/.test(t))return 'Cars';if(/jet|plane|yacht|watch|jewelry|diamond|luxury/.test(t))return 'Luxury';if(/invest|stake|venture|portfolio|fund/.test(t))return 'Investment';if(/deal|company|business|brand|acquisition|production budget/.test(t))return 'Business';if(/creator|stream|youtube|tiktok|influencer/.test(t))return 'Creator';return 'Spending';}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
async function fetchOne(q){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7500);try{const url='https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=en-US&gl=US&ceid=US:en';const r=await fetch(url,{signal:controller.signal,headers:{'user-agent':'Mozilla/5.0 (compatible; PocketWatch/0.6)'}});if(!r.ok)throw new Error('Google News HTTP '+r.status);return await r.text();}finally{clearTimeout(timer);}}
export async function fetchGoogleNews(){const results=await Promise.allSettled(QUERIES.map(fetchOne));const seen=new Map();const errors=[];results.forEach((res,i)=>{if(res.status==='rejected'){errors.push('query '+i+': '+(res.reason?.message||'request failed'));return;}for(const b of blocks(res.value)){const title=tag(b,'title'),desc=tag(b,'description'),published=tag(b,'pubDate')||tag(b,'published'),link=linkOf(b);const text=strip(title+' '+desc);const person=personFor(text);if(!person)continue;const amount=amountFor(text);const cat=category(text);const moneySignal=/bought|purchased|spent|purchase|bet|wager|investment|invested|mansion|house|jet|plane|yacht|car|watch|jewelry|deal|stake|contract|production budget|luxury/i.test(text);if(!moneySignal)continue;const key=hash((person+'|'+title).toLowerCase());if(seen.has(key))continue;seen.set(key,{id:key,name:person,initials:person.split(/\s+/).map(x=>x[0]).join('').slice(0,2),cat,amount:moneyLabel(amount),amountValue:amount,title:title||'Money move reported',desc:desc||title,status:amount!=null?'Reported':'Money story',source:sourceOf(b,link),sourceUrl:link,publishedAt:published||new Date().toISOString(),sourceType:'Google News RSS'});}});return {moves:[...seen.values()].sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,100),errors};}
export async function buildFeed(){const started=Date.now();let live={moves:[],errors:[]};try{live=await fetchGoogleNews();}catch(e){live.errors=[e.message||'Google News request failed'];}const demo=DEMO.map((x,i)=>({id:'demo-'+i,name:x[0],initials:x[0].split(/\s+/).map(y=>y[0]).join('').slice(0,2),cat:x[1],amount:moneyLabel(x[2]),amountValue:x[2],title:x[3],desc:x[4],status:x[5],source:x[6],sourceUrl:'https://news.google.com/',publishedAt:new Date(Date.now()-i*3600000).toISOString(),sourceType:'Demo fallback'}));const liveCount=live.moves.length;const moves=liveCount?live.moves:demo;return {source:liveCount?'Google News RSS':'Demo fallback',updatedAt:new Date().toISOString(),count:moves.length,liveCount,moves,errors:live.errors.slice(0,8),diagnostics:{durationMs:Date.now()-started,queries:QUERIES.length,liveItems:liveCount,usedFallback:!liveCount}};}
